const imagenesArray =  [ {
    id : `1`,
    nombre : "chañar",
    imagen : "./recursos/galeria/Chañar/Copia de DSC_0044.jpg",
    categoria : "chanar",
},
{
    nombre : "chañar",
    id : `1`,
    imagen : "./recursos/galeria/Chañar/Copia de 20220619_133403_HDR.jpg",
    categoria : "chanar",
},
{
    nombre : "chañar",
    id : `1`,
    imagen : "./recursos/galeria/Chañar/Copia de 20211106_125226_HDR.jpg",
    categoria : "chanar",
},
{
    nombre : "durazno de campo",
    id : `2`,
    imagen : "./recursos/galeria/Durazno-de-campo/Copia de DSC_0128.jpg",
    categoria : "durazno de campo",
},
{
    nombre : "chañar",
    id : `2`,
    imagen : "./recursos/galeria/Durazno-de-campo/Copia de DSC_0131.jpg",
    categoria : "durazno de campo",
},
{
    nombre : "chañar",
    id : `2`,
    imagen : "./recursos/galeria/Durazno-de-campo/Copia de DSC_0293 (2).jpg",
    categoria : "durazno de campo",
},

{
    nombre : "Algarrobo blanco alba",
    id : `3`,
    imagen : "./recursos/galeria/Algarrobo-blanco-alba/Copia de 20211106_130814_HDR.jpg",
    categoria : "Algarrobo-blanco-alba",
},

{
    nombre : "Algarrobo blanco alba",
    id : `3`,
    imagen : "./recursos/galeria/Algarrobo-blanco-alba/Copia de 20221108_122457_HDR.jpg",
    categoria : "Algarrobo-blanco-alba",
},
{
    nombre : "Algarrobo blanco alba",
    id : `3`,
    imagen : "./recursos/galeria/Algarrobo-blanco-alba/Copia de DSC_0169.jpg",
    categoria : "Algarrobo-blanco-alba",
},
{
    nombre : "Espinillo Caven",
    id : `4`,
    imagen : "./recursos/galeria/Espinillo-Caven/Copia de 20211106_124927_HDR.jpg",
    categoria : "Algarrobo-blanco-alba",
},
{
    nombre : "Espinillo Caven",
    id : `4`,
    imagen : "./recursos/galeria/Espinillo-Caven/Copia de DSC_0007.jpg",
    categoria : "Algarrobo-blanco-alba",
},
{
    nombre : "Espinillo Caven",
    id : `4`,
    imagen : "./recursos/galeria/Espinillo-Caven/Copia de DSC_0030.jpg",
    categoria : "Algarrobo-blanco-alba",
},
{
    nombre : "Lagaña de perro",
    id : `5`,
    imagen : "./recursos/galeria/Lagaña-de-perro/Copia de DSC_0108.jpg",
    categoria : "Lagaña-de-perro",
},
{
    nombre : "Lagaña de perro",
    id : `5`,
    imagen : "./recursos/galeria/Lagaña-de-perro/Copia de DSC_0299.jpg",
    categoria : "Lagaña-de-perro",
},
{
    nombre : "Lagaña de perro",
    id : `5`,
    imagen : "./recursos/galeria/Lagaña-de-perro/WhatsApp Image 2023-06-14 at 23.38.40.jpeg",
    categoria : "Lagaña-de-perro",
},
{
    nombre : "Manzano de campo",
    id : `6`,
    imagen : "./recursos/galeria/Manzano-de-campo/Copia de 20220322_114450.jpg",
    categoria : "Manzano-de-campo",
},
{
    nombre : "Manzano de campo",
    id : `6`,
    imagen : "./recursos/galeria/Manzano-de-campo/Copia de 20220619_132828_HDR.jpg",
    categoria : "Manzano-de-campo",
},
{
    nombre : "Manzano de campo",
    id : `6`,
    imagen : "./recursos/galeria/Manzano-de-campo/Copia de 20220619_133158_HDR.jpg",
    categoria : "Manzano-de-campo",
},
{
    nombre : "Molle",
    id : `7`,
    imagen : "./recursos/galeria/Molle/Copia de 20211009_154747_HDR.jpg",
    categoria : "Molle",
},
{
    nombre : "Molle",
    id : `7`,
    imagen : "./recursos/galeria/Molle/Copia de 20211106_133226_HDR.jpg",
    categoria : "Molle",
},
{
    nombre : "Molle",
    id : `7`,
    imagen : "./recursos/galeria/Molle/Copia de 20221009_114953_HDR.jpg",
    categoria : "Molle",
},
{
    nombre : "Moradillo",
    id : `8`,
    imagen : "./recursos/galeria/Moradillo/Copia de 20211009_154536_HDR.jpg",
    categoria : "Moradillo",
},
{
    nombre : "Moradillo",
    id : `8`,
    imagen : "./recursos/galeria/Moradillo/Copia de 20221009_115624.jpg",
    categoria : "Moradillo",
},
{
    nombre : "Moradillo",
    id : `8`,
    imagen : "./recursos/galeria/Moradillo/Copia de DSC_0047.jpg",
    categoria : "Moradillo",
},
{
    nombre : "Pichanilla",
    id : `9`,
    imagen : "./recursos/galeria/Pichanilla/20221009_120506_HDR.jpg",
    categoria : "Pichanilla",
},
{
    nombre : "Pichanilla",
    id : `9`,
    imagen : "./recursos/galeria/Pichanilla/DSC_0056.jpg",
    categoria : "Pichanilla",
},
{
    nombre : "Pichanilla",
    id : `9`,
    imagen : "./recursos/galeria/Pichanilla/DSC_0058.jpg",
    categoria : "Pichanilla",
},
{
    nombre : "Quebracho blanco",
    id : `10`,
    imagen : "./recursos/galeria/Quebracho-blanco/Copia de 20211002_165248_HDR.jpg",
    categoria : "Quebracho-blanco",
},
{
    nombre : "Quebracho blanco",
    id : `10`,
    imagen : "./recursos/galeria/Quebracho-blanco/Copia de 20211002_173525_HDR.jpg",
    categoria : "Quebracho-blanco",
},
{
    nombre : "Quebracho blanco",
    id : `10`,
    imagen : "./recursos/galeria/Quebracho-blanco/Copia de 20211009_013215_HDR.jpg",
    categoria : "Quebracho-blanco",
},
{
    nombre : "Sacha Guasca",
    id : `11`,
    imagen : "./recursos/galeria/Sacha-Guasca/Copia de 20220322_115736.jpg",
    categoria : "Sacha-Guasca",
},
{
    nombre : "Sacha Guasca",
    id : `11`,
    imagen : "./recursos/galeria/Sacha-Guasca/Copia de 20220420_113725_HDR.jpg",
    categoria : "Sacha-Guasca",
},
{
    nombre : "Sacha Guasca",
    id : `11`,
    imagen : "./recursos/galeria/Sacha-Guasca/Copia de DSC_0022.jpg",
    categoria : "Sacha-Guasca",
},
{
    nombre : "Sen de campo",
    id : `12`,
    imagen : "./recursos/galeria/Sen-de-campo/Copia de 20211014_094014_HDR.jpg",
    categoria : "Sen-de-campo",
},
{
    nombre : "Sen de campo",
    id : `12`,
    imagen : "./recursos/galeria/Sen-de-campo/Copia de 20220322_114335.jpg",
    categoria : "Sen-de-campo",
},
{
    nombre : "Sen de campo",
    id : `12`,
    imagen : "./recursos/galeria/Sen-de-campo/Copia de WhatsApp Image 2023-06-13 at 12.56.50 (1).jpeg",
    categoria : "Sen-de-campo",
},
{
    nombre : "Tala",
    id : `13`,
    imagen : "./recursos/galeria/Tala/Copia de 20211106_133608_HDR.jpg",
    categoria : "Tala",
},
{
    nombre : "Tala",
    id : `13`,
    imagen : "./recursos/galeria/Tala/Copia de 20220117_190335.jpg",
    categoria : "Tala",
},
{
    nombre : "Tala",
    id : `13`,
    imagen : "./recursos/galeria/Tala/Copia de DSC_0012.jpg",
    categoria : "Tala",
},
{
    nombre : "Tumiñico",
    id : `14`,
    imagen : "./recursos/galeria/Tumiñico/20211106_125302_HDR.jpg",
    categoria : "Tumiñico",
},
{
    nombre : "Tumiñico",
    id : `14`,
    imagen : "./recursos/galeria/Tumiñico/20211106_125337_HDR.jpg",
    categoria : "Tumiñico",
},
{
    nombre : "Tumiñico",
    id : `14`,
    imagen : "./recursos/galeria/Tumiñico/20220420_113113_HDR.jpg",
    categoria : "Tumiñico",
},
{
    nombre : "Tusca",
    id : `15`,
    imagen : "./recursos/galeria/Tusca/Copia de 20211106_123229_HDR.jpg",
    categoria : "Tusca",
},
{
    nombre : "Tusca",
    id : `15`,
    imagen : "./recursos/galeria/Tusca/Copia de 20220420_114103_HDR.jpg",
    categoria : "Tusca",
},
{
    nombre : "Tusca",
    id : `15`,
    imagen : "./recursos/galeria/Tusca/Copia de Tusca (Vachellia aroma). Isleta de nativas y son las que tienen inflorecencia amarillas. Fotografía virginiaprelato.jpg",
    categoria : "Tusca",
},

] ;        // Array de imagenes        